// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.School_dbModels;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20231115153335_SChool_db")]
    partial class SChool_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.School_dbModels.Class", b =>
                {
                    b.Property<int>("ClassDetails")
                        .HasColumnType("int")
                        .HasColumnName("CLass_Details");

                    b.Property<int>("Students")
                        .HasColumnType("int");

                    b.HasIndex("ClassDetails");

                    b.HasIndex("Students");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.ClassDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Class_Name");

                    b.Property<string>("ClassYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nchar(9)")
                        .HasColumnName("Class_Year")
                        .IsFixedLength();

                    b.Property<int>("CurricularUnit")
                        .HasColumnType("int")
                        .HasColumnName("Curricular_unit");

                    b.Property<int>("Teacher")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Class_De__3214EC07120FF06E");

                    b.HasIndex("CurricularUnit");

                    b.HasIndex("Teacher");

                    b.ToTable("Class_Details", (string)null);
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.CurricularUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Unit_Name");

                    b.HasKey("Id")
                        .HasName("PK__Curricul__3214EC07ABA75722");

                    b.ToTable("Curricular_Units", (string)null);
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Roles")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__People__3214EC07C47A38B6");

                    b.HasIndex("Roles");

                    b.ToTable("People");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Role_Description");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07ED32FE9C");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.Class", b =>
                {
                    b.HasOne("WebApplication2.School_dbModels.ClassDetail", "ClassDetailsNavigation")
                        .WithMany()
                        .HasForeignKey("ClassDetails")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Classes__CLass_D__2F10007B");

                    b.HasOne("WebApplication2.School_dbModels.Person", "StudentsNavigation")
                        .WithMany()
                        .HasForeignKey("Students")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__Student__300424B4");

                    b.Navigation("ClassDetailsNavigation");

                    b.Navigation("StudentsNavigation");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.ClassDetail", b =>
                {
                    b.HasOne("WebApplication2.School_dbModels.CurricularUnit", "CurricularUnitNavigation")
                        .WithMany("ClassDetails")
                        .HasForeignKey("CurricularUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Class_Det__Curri__2C3393D0");

                    b.HasOne("WebApplication2.School_dbModels.Person", "TeacherNavigation")
                        .WithMany("ClassDetails")
                        .HasForeignKey("Teacher")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Class_Det__Teach__2D27B809");

                    b.Navigation("CurricularUnitNavigation");

                    b.Navigation("TeacherNavigation");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.Person", b =>
                {
                    b.HasOne("WebApplication2.School_dbModels.Role", "RolesNavigation")
                        .WithMany("People")
                        .HasForeignKey("Roles")
                        .HasConstraintName("FK__People__Roles__276EDEB3");

                    b.Navigation("RolesNavigation");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.CurricularUnit", b =>
                {
                    b.Navigation("ClassDetails");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.Person", b =>
                {
                    b.Navigation("ClassDetails");
                });

            modelBuilder.Entity("WebApplication2.School_dbModels.Role", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
